name: flutter_frontend_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  fl_chart: ^0.66.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  flutter_markdown: ^0.7.3
  url_launcher: ^6.3.0
  video_player: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/assets/ai_display_config.json
    - lib/assets/bubbles_config.json
    - lib/assets/animation_chatbot.mp4
    - assets/avatar.png
    - assets/back_button.png
    - assets/payments.png
    - assets/spends.png
    - assets/transfer.png
    - assets/savings.png
    - assets/support.png
    - assets/search.png
